version: '3'
services:
  database:
    image: postgres:11-alpine
    restart: always
    env_file:
      - ./docker.env
  app:
    build: ./
    restart: always
    ports:
      - 8001:8001
    links:
      - "database:database"
  #   # depends_on:
  #     # - database
    env_file:
      - ./docker.env
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - app
