version: '3'
services:
  app:
    build: ./
    restart: always
    ports:
      - 8001:8001
    links:
      - "database:database"
    # volumes of static assets?
  database:
    image: postgresql:11-alpine
    restart: always
    # volumes?
