#! /usr/bin/env sh

set -e

echo "env DATABASE $DATABASE"
echo "env DATABASE_NAME $DATABASE_NAME"
echo "env DATABASE_USER $DATABASE_USER"
echo "env DATABASE_PASSWORD $DATABASE_PASSWORD"
echo "env DATABASE_HOST $DATABASE_HOST"
echo "env DATABASE_PORT $DATABASE_PORT"
echo "env CSRF_SESSION_KEY $CSRF_SESSION_KEY"
echo "env GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID"
echo "env GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET"

exec $@
